resources:
  - operator-base
transformers:
  - site-config/transformer.yaml
  - site-config/mirror.yaml
  ## Uncomment the following inclusion if you are deploying the
  ## operator in clusterwide mode.
  #- site-config/cluster-wide-transformer.yaml
  ## Uncomment the following inclusion if you are deploying the
  ## operator in a cluster that does not support seccomp.
  - site-config/remove-seccomp-transformer.yaml
secretGenerator:
- name: site-image-pull-secret
  type: kubernetes.io/dockerconfigjson
  files:
  - .dockerconfigjson=site-config/image-pull-secret.json
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: site-image-pull-secret
  target:
    kind: Deployment
    name: sas-deployment-operator
